---
- name: Install nftables
  tags: nftables
  apt:
    cache_valid_time: 86400
    name: nftables

- name: create config dir
  tags: nftables
  file:
    path: /etc/ooni/nftables/tcp
    state: directory
    owner: root
    group: root
    mode: 0755

- name: allow SSH
  tags: nftables
  blockinfile:
    path: /etc/ooni/nftables/tcp/22.nft
    create: yes
    block: |
      add rule inet filter input tcp dport 22 counter accept comment "Incoming SSH"

- name: Overwrite nftables.conf
  tags: nftables
  template:
    src: templates/nftables.conf
    dest: /etc/nftables.conf
    mode: 0755
    owner: root

- name: enable nftables service
  tags: nftables
  shell: systemctl enable nftables.service

- name: enable nftables service
  tags: nftables
  shell: systemctl start nftables.service

#- name: Enable and start nftables service
#  systemd:
#    name: nftables.service
#    state: reloaded
#    enabled: yes

- name: reload nftables service
  tags: nftables
  shell: systemctl reload nftables.service
