---
- hosts: backend-hel.ooni.org
  roles:
    - role: base-bookworm
    - role: nftables
    - role: nginx-buster
      tags: nginx
    - role: dehydrated
      tags: dehydrated
      expand: yes
      ssl_domains:
        # with dehydrated the first entry is the cert FQDN
        # and the other ones are alternative names
        - "backend-hel.ooni.org"
    - role: ooni-backend
      ssl_domain: backend-hel.ooni.org
