---
- name: Ensure all hosts are bootstrapped correctly
  hosts: all
  become: yes
  roles:
    - bootstrap
  tags:
    - bootstrap

- name: Include tier0 playbook
  ansible.builtin.import_playbook: deploy-tier0.yml

- name: Include tier2 playbook
  ansible.builtin.import_playbook: deploy-tier2.yml
